### ISSUE TITLE
Attempted isUserIdentifiable on user who isn't even in the db

### ISSUE THREAD

**Issue by utybo** [EpiLink/EpiLink#121]
```
org.epilink.bot.LinkException: Unknown user [REDACTED]
	at org.epilink.bot.db.exposed.ExposedDatabaseFacade.isUserIdentifiable$suspendImpl(ExposedFacadeImpl.kt:109)
	at org.epilink.bot.db.exposed.ExposedDatabaseFacade.isUserIdentifiable(ExposedFacadeImpl.kt)
	at org.epilink.bot.db.LinkServerDatabaseImpl.isUserIdentifiable(LinkServerDatabase.kt:210)
	at org.epilink.bot.http.LinkBackEndImpl.toUserInformation(LinkBackEnd.kt:429)
	at org.epilink.bot.http.LinkBackEndImpl$epilinkApiV1$3$1$2.invokeSuspend(LinkBackEnd.kt:189)
	at org.epilink.bot.http.LinkBackEndImpl$epilinkApiV1$3$1$2.invoke(LinkBackEnd.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
	at org.epilink.bot.http.LinkBackEndImpl$epilinkApiV1$3$1$1.invokeSuspend(LinkBackEnd.kt:181)
	at org.epilink.bot.http.LinkBackEndImpl$epilinkApiV1$3$1$1.invoke(LinkBackEnd.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
	at org.epilink.bot.ratelimiting.RateLimiting.handleRateLimitedCall$epilink_backend(RateLimiting.kt:220)
	at org.epilink.bot.ratelimiting.RateLimitingKt$rateLimited$2.invokeSuspend(RateLimiting.kt:258)
	at org.epilink.bot.ratelimiting.RateLimitingKt$rateLimited$2.invoke(RateLimiting.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
	at org.epilink.bot.http.LinkBackEndImpl$epilinkApiV1$1$1.invokeSuspend(LinkBackEnd.kt:129)
	at org.epilink.bot.http.LinkBackEndImpl$epilinkApiV1$1$1.invoke(LinkBackEnd.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:177)
	at org.epilink.bot.http.LinkBackEndImpl$epilinkApiV1$1.invokeSuspend(LinkBackEnd.kt:128)
	at org.epilink.bot.http.LinkBackEndImpl$epilinkApiV1$1.invoke(LinkBackEnd.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
	at io.ktor.routing.Routing.executeResult(Routing.kt:147)
	at io.ktor.routing.Routing.interceptor(Routing.kt:34)
	at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:99)
	at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:144)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by utybo** [comment]
This happens because Redis maintained a session about a user who did not exist anymore in the database.

Fix: not only validate the presence of a user session, but also validate the fact that they still exist in the DB
